# Generated by Django 5.0.2 on 2024-02-24 06:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='课程编号')),
                ('courseName', models.CharField(max_length=100, unique=True, verbose_name='课程名称')),
                ('credit', models.IntegerField(verbose_name='学分')),
                ('classifier', models.SmallIntegerField(choices=[('A', '纯理论课'), ('B', '理论+实践'), ('C', '纯实践课')], verbose_name='课程类别')),
                ('attribute', models.SmallIntegerField(choices=[(1, '通识性课程'), (1, '公共选修课'), (3, '专业基础课'), (4, '专业必修课'), (5, '专业选修课'), (6, '素质拓展课'), (7, '独立实践环节')], verbose_name='课程属性')),
                ('semester', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid date in the format YYYY-MM-DD', regex='第\\s*(\\d+)\\s*学期')], verbose_name='课程所属学期')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='学院编号')),
                ('departmentName', models.CharField(max_length=100, unique=True, verbose_name='学院名称')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='专业代号')),
                ('majorName', models.CharField(max_length=100, unique=True, verbose_name='专业名称')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userclient.department', verbose_name='专业所属学院')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupName', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='班级')),
                ('grade', models.SmallIntegerField(verbose_name='班级所属年级')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userclient.course', to_field='courseName', verbose_name='分配课程')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userclient.major', to_field='majorName', verbose_name='班级所在专业')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='学生姓名')),
                ('idNumber', models.CharField(max_length=18, unique=True, verbose_name='身份证号码')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('ethnicity', models.CharField(default='汉族', max_length=10, verbose_name='民族')),
                ('enterYear', models.DateField(verbose_name='入学年份')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userclient.department', to_field='departmentName', verbose_name='所在学院')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userclient.group', verbose_name='所在班级')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userclient.major', to_field='majorName', verbose_name='所在专业')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='教师工号')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='教师姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userclient.department', verbose_name='学院（部门）')),
            ],
        ),
    ]
