# Generated by Django 5.0.2 on 2024-02-24 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userclient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userclient.department', to_field='departmentName', verbose_name='专业所属学院'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userclient.department', to_field='departmentName', verbose_name='学院（部门）'),
        ),
    ]
