# Generated by Django 5.0.2 on 2024-02-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userclient', '0004_author_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='SuperAdmin',
        ),
    ]
