# Generated by Django 5.0.2 on 2024-02-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userclient', '0005_rename_book_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
    ]
