# Generated by Django 5.0.2 on 2024-02-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userclient', '0007_alter_course_attribute_alter_course_classifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '班级库', 'verbose_name_plural': '班级库'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '学院信息表', 'verbose_name_plural': '学院信息表'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '班级库', 'verbose_name_plural': '班级库'},
        ),
        migrations.AlterModelOptions(
            name='major',
            options={'verbose_name': '专业库', 'verbose_name_plural': '专业库'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生库', 'verbose_name_plural': '学生库'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师库', 'verbose_name_plural': '教师库'},
        ),
    ]
